Add connection to MongoDB
agiledev-students-spring-2023/final-project-finishit pull request #102
Opened 2023-04-14 19:08 UTC by hpdouglass

2023-04-15 18:37 UTC, Bast1onic requested changes
`mongoose.connect` returns a promise. I would recommend using .then and .catch instead of try/catch, because with how you've currently written the connection statement "Connected to MongoDB" will be printed before an actual connection is made.

2023-04-15 18:37 UTC, Bast1onic commented on back-end/app.js
> +    console.log('Connected to MongoDB.')
`mongoose.connect` is an asynchronous operation and so returns a promise. You need to add `await` on line 27 or line 28 will be executed before an actual connection is made.

2023-04-16 16:12 UTC, hpdouglass commented on back-end/app.js
> +    console.log('Connected to MongoDB.')
Thanks for the feedback! This should now be implemented as you've described. I've tested it with both the correct MongoDB string and a bad one to test error handling. Everything seems to be working as expected!

In case you're curious, the original code I used was based off the professor's data storage example app, [where he used a try/catch instead of handling the promise properly](https://github.com/nyu-software-engineering/data-storage-example-app/blob/master/back-end/app.js#L28).

2023-04-16 18:51 UTC, Bast1onic approved these changes
Looks good.

2023-04-16 18:51 UTC, merged